SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `aktivitas_kuliah_mahasiswa` ADD CONSTRAINT `fk_akm_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `aktivitas_kuliah_mahasiswa` ADD CONSTRAINT `fk_akm_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON UPDATE CASCADE;
ALTER TABLE `aktivitas_mahasiswa` ADD CONSTRAINT `fk_aktivitas_mhs_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `aktivitas_mahasiswa` ADD CONSTRAINT `fk_aktivitas_mhs_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `aktivitas_mahasiswa_anggota` ADD CONSTRAINT `fk_aktivitas_anggota_aktivitas` FOREIGN KEY (`id_aktivitas_mahasiswa`) REFERENCES `aktivitas_mahasiswa` (`id_aktivitas_mahasiswa`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `aktivitas_mahasiswa_anggota` ADD CONSTRAINT `fk_aktivitas_anggota_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `aktivitas_mahasiswa_pembimbing` ADD CONSTRAINT `fk_aktivitas_pembimbing_aktivitas` FOREIGN KEY (`id_aktivitas_mahasiswa`) REFERENCES `aktivitas_mahasiswa` (`id_aktivitas_mahasiswa`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `aktivitas_mahasiswa_pembimbing` ADD CONSTRAINT `fk_aktivitas_pembimbing_dosen` FOREIGN KEY (`id_dosen`) REFERENCES `dosen` (`id_dosen`) ON UPDATE CASCADE;
ALTER TABLE `dosen` ADD CONSTRAINT `fk_dosen_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `dosen` ADD CONSTRAINT `fk_dosen_users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `dosen_pengajar_kelas` ADD CONSTRAINT `fk_dosen_pengajar_dosen` FOREIGN KEY (`id_dosen`) REFERENCES `dosen` (`id_dosen`) ON UPDATE CASCADE;
ALTER TABLE `dosen_pengajar_kelas` ADD CONSTRAINT `fk_dosen_pengajar_kelas_kuliah` FOREIGN KEY (`id_kelas_kuliah`) REFERENCES `kelas_kuliah` (`id_kelas_kuliah`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `email_log` ADD CONSTRAINT `fk_email_log_user` FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `jadwal_kuliah` ADD CONSTRAINT `fk_jadwal_dosen` FOREIGN KEY (`id_dosen`) REFERENCES `dosen` (`id_dosen`) ON UPDATE CASCADE;
ALTER TABLE `jadwal_kuliah` ADD CONSTRAINT `fk_jadwal_kelas` FOREIGN KEY (`id_kelas`) REFERENCES `kelas` (`id_kelas`) ON UPDATE CASCADE;
ALTER TABLE `jadwal_kuliah` ADD CONSTRAINT `fk_jadwal_mk` FOREIGN KEY (`id_mk`) REFERENCES `mata_kuliah` (`id_mk`) ON UPDATE CASCADE;
ALTER TABLE `jadwal_kuliah` ADD CONSTRAINT `fk_jadwal_ruangan` FOREIGN KEY (`id_ruangan`) REFERENCES `ruangan` (`id_ruangan`) ON UPDATE CASCADE;
ALTER TABLE `jadwal_kuliah` ADD CONSTRAINT `fk_jadwal_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON UPDATE CASCADE;
ALTER TABLE `kelas` ADD CONSTRAINT `fk_kelas_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON UPDATE CASCADE;
ALTER TABLE `kelas` ADD CONSTRAINT `fk_kelas_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON UPDATE CASCADE;
ALTER TABLE `kelas_kuliah` ADD CONSTRAINT `fk_kelas_kuliah_internal` FOREIGN KEY (`id_kelas_internal`) REFERENCES `kelas` (`id_kelas`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `kelas_kuliah` ADD CONSTRAINT `fk_kelas_kuliah_jadwal` FOREIGN KEY (`id_jadwal`) REFERENCES `jadwal_kuliah` (`id_jadwal`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `kelas_kuliah` ADD CONSTRAINT `fk_kelas_kuliah_mk` FOREIGN KEY (`id_mk`) REFERENCES `mata_kuliah` (`id_mk`) ON UPDATE CASCADE;
ALTER TABLE `kelas_kuliah` ADD CONSTRAINT `fk_kelas_kuliah_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON UPDATE CASCADE;
ALTER TABLE `kelas_kuliah` ADD CONSTRAINT `fk_kelas_kuliah_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON UPDATE CASCADE;
ALTER TABLE `khs` ADD CONSTRAINT `fk_khs_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `khs` ADD CONSTRAINT `fk_khs_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON UPDATE CASCADE;
ALTER TABLE `konversi_mbkm` ADD CONSTRAINT `fk_konversi_mbkm_aktivitas` FOREIGN KEY (`id_aktivitas_mahasiswa`) REFERENCES `aktivitas_mahasiswa` (`id_aktivitas_mahasiswa`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `konversi_mbkm` ADD CONSTRAINT `fk_konversi_mbkm_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `konversi_mbkm` ADD CONSTRAINT `fk_konversi_mbkm_mk` FOREIGN KEY (`id_mk`) REFERENCES `mata_kuliah` (`id_mk`) ON UPDATE CASCADE;
ALTER TABLE `krs` ADD CONSTRAINT `fk_krs_dosen_pa` FOREIGN KEY (`disetujui_oleh`) REFERENCES `dosen` (`id_dosen`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `krs` ADD CONSTRAINT `fk_krs_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `krs` ADD CONSTRAINT `fk_krs_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON UPDATE CASCADE;
ALTER TABLE `krs_detail` ADD CONSTRAINT `fk_krs_detail_jadwal` FOREIGN KEY (`id_jadwal`) REFERENCES `jadwal_kuliah` (`id_jadwal`) ON UPDATE CASCADE;
ALTER TABLE `krs_detail` ADD CONSTRAINT `fk_krs_detail_krs` FOREIGN KEY (`id_krs`) REFERENCES `krs` (`id_krs`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `kurikulum` ADD CONSTRAINT `fk_kurikulum_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON UPDATE CASCADE;
ALTER TABLE `log_aktivitas` ADD CONSTRAINT `fk_log_user` FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `login_log` ADD CONSTRAINT `fk_login_log_user` FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `mahasiswa` ADD CONSTRAINT `fk_mahasiswa_kelas` FOREIGN KEY (`id_kelas`) REFERENCES `kelas` (`id_kelas`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `mahasiswa` ADD CONSTRAINT `fk_mahasiswa_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON UPDATE CASCADE;
ALTER TABLE `mahasiswa` ADD CONSTRAINT `fk_mahasiswa_users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `mahasiswa_lulus_do` ADD CONSTRAINT `fk_lulus_do_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `mahasiswa_lulus_do` ADD CONSTRAINT `fk_lulus_do_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `mata_kuliah` ADD CONSTRAINT `fk_mk_kurikulum` FOREIGN KEY (`id_kurikulum`) REFERENCES `kurikulum` (`id_kurikulum`) ON UPDATE CASCADE;
ALTER TABLE `matkul_kurikulum` ADD CONSTRAINT `fk_matkul_kurikulum_kurikulum` FOREIGN KEY (`id_kurikulum`) REFERENCES `kurikulum` (`id_kurikulum`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `matkul_kurikulum` ADD CONSTRAINT `fk_matkul_kurikulum_mk` FOREIGN KEY (`id_mk`) REFERENCES `mata_kuliah` (`id_mk`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `nilai` ADD CONSTRAINT `fk_nilai_dosen` FOREIGN KEY (`input_by`) REFERENCES `dosen` (`id_dosen`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `nilai` ADD CONSTRAINT `fk_nilai_krs_detail` FOREIGN KEY (`id_krs_detail`) REFERENCES `krs_detail` (`id_krs_detail`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `notifikasi` ADD CONSTRAINT `fk_notifikasi_user` FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `pembayaran_mahasiswa` ADD CONSTRAINT `fk_pembayaran_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `pembayaran_mahasiswa` ADD CONSTRAINT `fk_pembayaran_tagihan` FOREIGN KEY (`id_tagihan`) REFERENCES `tagihan_mahasiswa` (`id_tagihan`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `pembayaran_mahasiswa` ADD CONSTRAINT `fk_pembayaran_verifikator` FOREIGN KEY (`diverifikasi_oleh`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `pendaftar_pmb` ADD CONSTRAINT `fk_pmb_gelombang` FOREIGN KEY (`id_gelombang`) REFERENCES `pmb_gelombang` (`id_gelombang`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `pendaftar_pmb` ADD CONSTRAINT `fk_pmb_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `pendaftar_pmb` ADD CONSTRAINT `fk_pmb_prodi` FOREIGN KEY (`id_prodi_pilihan`) REFERENCES `prodi` (`id_prodi`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `pendaftar_pmb` ADD CONSTRAINT `fk_pmb_verifikator` FOREIGN KEY (`diverifikasi_oleh`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `peserta_kelas_kuliah` ADD CONSTRAINT `fk_peserta_kelas_kuliah` FOREIGN KEY (`id_kelas_kuliah`) REFERENCES `kelas_kuliah` (`id_kelas_kuliah`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `peserta_kelas_kuliah` ADD CONSTRAINT `fk_peserta_krs` FOREIGN KEY (`id_krs`) REFERENCES `krs` (`id_krs`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `peserta_kelas_kuliah` ADD CONSTRAINT `fk_peserta_krs_detail` FOREIGN KEY (`id_krs_detail`) REFERENCES `krs_detail` (`id_krs_detail`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `peserta_kelas_kuliah` ADD CONSTRAINT `fk_peserta_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `peserta_wisuda` ADD CONSTRAINT `fk_peserta_wisuda_header` FOREIGN KEY (`id_wisuda`) REFERENCES `wisuda` (`id_wisuda`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `peserta_wisuda` ADD CONSTRAINT `fk_peserta_wisuda_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `peserta_wisuda` ADD CONSTRAINT `fk_peserta_wisuda_yudisium` FOREIGN KEY (`id_yudisium`) REFERENCES `yudisium` (`id_yudisium`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `peserta_yudisium` ADD CONSTRAINT `fk_peserta_yudisium_header` FOREIGN KEY (`id_yudisium`) REFERENCES `yudisium` (`id_yudisium`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `peserta_yudisium` ADD CONSTRAINT `fk_peserta_yudisium_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `peserta_yudisium` ADD CONSTRAINT `fk_peserta_yudisium_ta` FOREIGN KEY (`id_ta`) REFERENCES `tugas_akhir` (`id_ta`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `presensi_kuliah` ADD CONSTRAINT `fk_presensi_jadwal` FOREIGN KEY (`id_jadwal`) REFERENCES `jadwal_kuliah` (`id_jadwal`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `presensi_kuliah` ADD CONSTRAINT `fk_presensi_kelas_kuliah` FOREIGN KEY (`id_kelas_kuliah`) REFERENCES `kelas_kuliah` (`id_kelas_kuliah`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `presensi_kuliah` ADD CONSTRAINT `fk_presensi_user` FOREIGN KEY (`dibuat_oleh`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `presensi_mahasiswa` ADD CONSTRAINT `fk_presensi_mhs_header` FOREIGN KEY (`id_presensi_kuliah`) REFERENCES `presensi_kuliah` (`id_presensi_kuliah`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `presensi_mahasiswa` ADD CONSTRAINT `fk_presensi_mhs_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `presensi_mahasiswa` ADD CONSTRAINT `fk_presensi_mhs_peserta` FOREIGN KEY (`id_peserta_kelas`) REFERENCES `peserta_kelas_kuliah` (`id_peserta_kelas`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `prestasi_mahasiswa` ADD CONSTRAINT `fk_prestasi_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `riwayat_status_mahasiswa` ADD CONSTRAINT `fk_riwayat_status_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `riwayat_status_mahasiswa` ADD CONSTRAINT `fk_riwayat_status_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `sync_attempts` ADD CONSTRAINT `fk_sync_attempts_queue` FOREIGN KEY (`id_queue`) REFERENCES `sync_queue` (`id_queue`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `sync_conflicts` ADD CONSTRAINT `fk_sync_conflicts_user` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `sync_queue` ADD CONSTRAINT `fk_sync_queue_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `ta_jadwal` ADD CONSTRAINT `fk_ta_jadwal_ruangan` FOREIGN KEY (`id_ruangan`) REFERENCES `ruangan` (`id_ruangan`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `ta_jadwal` ADD CONSTRAINT `fk_ta_jadwal_ta` FOREIGN KEY (`id_ta`) REFERENCES `tugas_akhir` (`id_ta`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ta_nilai` ADD CONSTRAINT `fk_ta_nilai_dosen` FOREIGN KEY (`id_dosen`) REFERENCES `dosen` (`id_dosen`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `ta_nilai` ADD CONSTRAINT `fk_ta_nilai_ta` FOREIGN KEY (`id_ta`) REFERENCES `tugas_akhir` (`id_ta`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ta_pembimbing` ADD CONSTRAINT `fk_ta_pembimbing_dosen` FOREIGN KEY (`id_dosen`) REFERENCES `dosen` (`id_dosen`) ON UPDATE CASCADE;
ALTER TABLE `ta_pembimbing` ADD CONSTRAINT `fk_ta_pembimbing_ta` FOREIGN KEY (`id_ta`) REFERENCES `tugas_akhir` (`id_ta`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ta_penguji` ADD CONSTRAINT `fk_ta_penguji_dosen` FOREIGN KEY (`id_dosen`) REFERENCES `dosen` (`id_dosen`) ON UPDATE CASCADE;
ALTER TABLE `ta_penguji` ADD CONSTRAINT `fk_ta_penguji_ta` FOREIGN KEY (`id_ta`) REFERENCES `tugas_akhir` (`id_ta`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `tagihan_mahasiswa` ADD CONSTRAINT `fk_tagihan_jenis_biaya` FOREIGN KEY (`id_jenis_biaya`) REFERENCES `jenis_biaya` (`id_jenis_biaya`) ON UPDATE CASCADE;
ALTER TABLE `tagihan_mahasiswa` ADD CONSTRAINT `fk_tagihan_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `tagihan_mahasiswa` ADD CONSTRAINT `fk_tagihan_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `tagihan_mahasiswa` ADD CONSTRAINT `fk_tagihan_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `tugas_akhir` ADD CONSTRAINT `fk_ta_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE;
ALTER TABLE `users` ADD CONSTRAINT `fk_users_roles` FOREIGN KEY (`id_role`) REFERENCES `roles` (`id_role`) ON UPDATE CASCADE;
ALTER TABLE `whatsapp_log` ADD CONSTRAINT `fk_whatsapp_log_user` FOREIGN KEY (`id_user`) REFERENCES `users` (`id_user`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `yudisium` ADD CONSTRAINT `fk_yudisium_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON DELETE SET NULL ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;
