CREATE TABLE IF NOT EXISTS dosen_penugasan_feeder (
    id_penugasan INT AUTO_INCREMENT PRIMARY KEY,
    id_registrasi_dosen_feeder VARCHAR(100) NULL,
    id_dosen INT NULL,
    id_dosen_feeder VARCHAR(100) NULL,
    nidn VARCHAR(30) NULL,
    nama_dosen VARCHAR(150) NULL,
    jenis_kelamin CHAR(1) NULL,
    nuptk VARCHAR(30) NULL,
    id_prodi INT NULL,
    id_prodi_feeder VARCHAR(100) NULL,
    nama_program_studi VARCHAR(150) NULL,
    id_tahun_ajaran_feeder VARCHAR(20) NULL,
    nama_tahun_ajaran VARCHAR(50) NULL,
    id_perguruan_tinggi_feeder VARCHAR(100) NULL,
    nama_perguruan_tinggi VARCHAR(200) NULL,
    nomor_surat_tugas VARCHAR(150) NULL,
    tanggal_surat_tugas DATE NULL,
    mulai_surat_tugas DATE NULL,
    tanggal_create_feeder DATE NULL,
    tanggal_ptk_keluar DATE NULL,
    id_status_pegawai_feeder VARCHAR(50) NULL,
    id_jenis_keluar_feeder VARCHAR(50) NULL,
    id_ikatan_kerja_feeder VARCHAR(50) NULL,
    is_homebase TINYINT(1) DEFAULT 0,
    raw_feeder_data LONGTEXT NULL,
    status_sync_feeder ENUM('belum','sudah','gagal') DEFAULT 'sudah',
    last_sync_feeder DATETIME NULL,
    last_error_feeder TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_penugasan_registrasi (id_registrasi_dosen_feeder),
    KEY idx_penugasan_dosen_feeder (id_dosen_feeder),
    KEY idx_penugasan_dosen_lokal (id_dosen),
    KEY idx_penugasan_prodi_feeder (id_prodi_feeder),
    KEY idx_penugasan_prodi_lokal (id_prodi),
    KEY idx_penugasan_tahun (id_tahun_ajaran_feeder)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
