CREATE TABLE IF NOT EXISTS `transkrip_mahasiswa` (
  `id_transkrip` int(11) NOT NULL AUTO_INCREMENT,
  `id_mahasiswa` int(11) NOT NULL,
  `id_registrasi_mahasiswa_feeder` varchar(100) DEFAULT NULL,
  `id_prodi` int(11) DEFAULT NULL,
  `id_prodi_feeder` varchar(100) DEFAULT NULL,
  `id_tahun` int(11) DEFAULT NULL,
  `id_semester_feeder` varchar(20) DEFAULT NULL,
  `id_matkul` int(11) DEFAULT NULL,
  `id_matkul_feeder` varchar(100) DEFAULT NULL,
  `kode_mk` varchar(50) DEFAULT NULL,
  `nama_mk` varchar(200) DEFAULT NULL,
  `sks_mk` int(11) DEFAULT 0,
  `nilai_angka` decimal(5,2) DEFAULT 0.00,
  `nilai_huruf` varchar(5) DEFAULT NULL,
  `nilai_indeks` decimal(4,2) DEFAULT 0.00,
  `raw_feeder_data` longtext DEFAULT NULL,
  `status_sync_feeder` enum('belum','sudah','gagal') DEFAULT 'sudah',
  `last_sync_feeder` datetime DEFAULT NULL,
  `last_error_feeder` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_transkrip`),
  UNIQUE KEY `uniq_transkrip_mhs_matkul_feeder` (`id_mahasiswa`, `id_matkul_feeder`),
  UNIQUE KEY `uniq_transkrip_mhs_kode_mk` (`id_mahasiswa`, `kode_mk`),
  KEY `idx_transkrip_registrasi_feeder` (`id_registrasi_mahasiswa_feeder`),
  KEY `idx_transkrip_semester_feeder` (`id_semester_feeder`),
  KEY `idx_transkrip_prodi` (`id_prodi`),
  KEY `idx_transkrip_matkul` (`id_matkul`),
  CONSTRAINT `fk_transkrip_mahasiswa` FOREIGN KEY (`id_mahasiswa`) REFERENCES `mahasiswa` (`id_mahasiswa`) ON UPDATE CASCADE,
  CONSTRAINT `fk_transkrip_prodi` FOREIGN KEY (`id_prodi`) REFERENCES `prodi` (`id_prodi`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_transkrip_tahun` FOREIGN KEY (`id_tahun`) REFERENCES `tahun_akademik` (`id_tahun`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_transkrip_matkul` FOREIGN KEY (`id_matkul`) REFERENCES `mata_kuliah` (`id_mk`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
